[package]
name = "web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.183"
yew = { version = "0.20.0", features = ["csr"] }
yewdux = "0.9.3"
